### ISSUE TITLE
feature: application run profile support

### ISSUE THREAD

**Issue by s1n7ax** [nvim-java/nvim-java#110]
Requirement:
- User should be able to create a run profile/profiles
- User should be able to pick and run using a run profile
- In a profile, user should be able to include project specific information

@TODO we should look into how and what information intelij stores
@TODO we should look into if we can do run and debug both
@TODO we should look into if overseer can be used on things like this

**Comment by atm1020** [comment]
@s1n7ax  

1. IntelliJ creates a workspace.xml file in the {project_directory}/.idea folder, where it stores profile information. As an example, I've set up a configuration with VM arguments and program arguments ( I believe these are the most commonly used settings, so I've focused on them in the nvim options as well) . 
![image](https://github.com/nvim-java/nvim-java/assets/30997516/cb3b1c46-ccbb-4492-94f7-9fce92ab0c00)

3. it's possible to pass VM and program arguments for both running and debugging. For the debugging option, after selecting a new profile, you need to reconfigure DAP to load the new arguments.   One little downside is that if you're running an application with profile1 and you switch to profile2, you need to stop the session and start a new one to use the profile2.


4. I think overseer little overhead in this case, because the run/debug commands are already available for us, and simpler user interface is better for profile changes and creation.

### POC:

Since nvim.nui is already in use, I focused on creating a small UI with it for creating, editing, and changing the active profile.

https://github.com/nvim-java/nvim-java/assets/30997516/acfa5702-19f6-414c-a646-d31178be8cd0

#### Profile ui
* Open with  `JavaProfile` command
* Create Profile
   * Select the `new profile` option to create a new one (press enter/space)
   * Press `s` in normal mode to save.
   * The new profile is set active by defult.
* Update
  * Select profile to edit (press enter/space)
   * Press `s` in normal mode to save.
* Set Active
  *  Press `a` in normal mode in  a list

All  Key binding (in normal mode) : 
* Profile List:
    * `j`: Down
    * `k`: Up
    * `space`: Edit
    * `enter`: Edit
    * `b`: Quit/Back
    * `q`: Quit
    * `a`: Set Active
    * `d`: Delete
* Profile Edit:
    * `b`: Back
    * `q`: Quit
    * `s`: Save

The profile config is saved to a JSON file named `nvim-java-profiles.json` in the `~/.local/share/nvim` folder. Saving to the project folder to the .config.json file or something like that, similar to what IntelliJ does, is still a possible option, but for dev/testing, one config feels more manageable.

json structure: 
```json
{
 "project_folder": {
    "profile_name1": {
      "vm_arg": "Vm-arg",
      "prog_arg": "Prog-arg",    
      "profile_name": "profile_name1"
 }
}

```

* You can test this on the https://github.com/atm1020/nvim-java/tree/feature-profile branch which I created from `nvim-java/feature-api-to-run-application` branch.
* The key bindings and the config folder is still a questionable for me.

**Comment by s1n7ax** [comment]
Awesome work @atm1020. Thanks for contributing.
