### ISSUE TITLE
Couldn't find package Openjdk-17

### ISSUE THREAD

**Issue by Samthesurf** [nvim-java/nvim-java#118]
I downloaded my openjdk-17 with pacman on my Arch system but everytime, I open Neovim, the extension opens up Mason and then it tells me it couldn't find openjdk-17 even tho it's installed. Please what do I do to fix it?

**Comment by s1n7ax** [comment]
@Samthesurf Mason will automatically install openjdk-17 you don't have to manually install it in the system level. However, it seems the registry is not correctly added and that's why it complains about the openjdk-17 not being found. A lot of the time it's due to the way a lot of people configure the mason plugin. See the following thread. https://github.com/nvim-java/nvim-java/issues/79

**Comment by Samthesurf** [comment]
I followed the config there, it installed the Mason_Installer but it still can't find the openjdk-17 package

**Comment by s1n7ax** [comment]
What does your mason setup configuration look like?

**Comment by Samthesurf** [comment]
[This it it] (https://github.com/Samthesurf/Samuel-s-Neovim-config/blob/master/lua%2Fplugins%2Fmason.lua)

**Comment by s1n7ax** [comment]
@Samthesurf You are literally doing what I have mentioned here. https://github.com/nvim-java/nvim-java/issues/79#issuecomment-1856161377 When you setup mason, get the default values passed from lazy.

**Comment by s1n7ax** [comment]
@Samthesurf I have added this issue to Q&A. You can refer this guide to configure mason correctly.

https://github.com/nvim-java/nvim-java/wiki/Q-&-A#no_entry-cannot-find-package-xxxxx
