### ISSUE TITLE
bug: jdtls is not using jdk-21

### ISSUE THREAD

**Issue by kyerpotts** [nvim-java/nvim-java#204]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0 release

### Operating system/version

Arch Linux

### Describe the bug

My default version of Java is 21, and I have set the default java path in lspconfig to the binary. When I attempt to run or debug, I receive an UnsupportedClassVersionError. I believe this is because openjdk-17 is hardcoded into the nvim-java plugin for builds, however it uses the specified runtime binary configured by lspconfig. I have resolved the issue by setting my default java runtime version to 17 and updating the required path, however it would be useful to be able to change the javac version as a config for the nvim-java in order to avoid ClassVersionErrors.

### Steps To Reproduce

1. Install java 21 using sdkman
2. Set up nvim-java
3. set up mason, mason-lspconfig and lspconfig.
5. setup jdtls using lspconfig.
`
require("lspconfig").jdtls.setup({
  settings = {
    java = {
      configuration = {
        runtimes = {
          {
            name = "JavaSE-21",
            path ="/PATH/TO/JAVA/RUNTIME/21",
            default = true,
          },
        },
      },
`
6. Run debugger / JavaRunnerRunMain

### Expected Behavior

nvim-java should use the same javac version as the currently specified runtime version configured by jdtls. An option to set the sdk used by nvim-java would also fix this issue.

**Comment by s1n7ax** [comment]
Try removing.classpath file and cache in ~/.cache/nvim/jdtld

**Comment by kyerpotts** [comment]
Tried this suggestion, jdtls builds using  openjdk-21 when the project loads, however the runner and debugger in nvim-java keep trying to run the build using openjdk-17

**Comment by s1n7ax** [comment]
@kyerpotts Sounds impossible. We retrieve the java executable information from `jdtls` meaning, if jdtls uses openjdk-21 for LS, it should be the same for run and debug as well. Has to be some cache issue. But try

```lua
jdk = {
  -- install jdk using mason.nvim
  auto_install = true,
}
```

When setup. This will disable auto installation of jdk 17. Then remove the JDK from `mason`. Clear the `.classpaths`, `.projects` & `jdtls` cache. Make sure you have not set jdk-17 as the runtime in pom.xml. Try again.

**Comment by s1n7ax** [comment]
@kyerpotts
https://github.com/nvim-java/nvim-java/wiki/Q-&-A#no_entry-how-to-clean-rebuild

**Comment by s1n7ax** [comment]
@kyerpotts 
Additionally, add this to make sure

```
    String version = System.getProperty("java.version");
    System.out.println(">>>>>>>>>" + version);

```

**Comment by kyerpotts** [comment]
On further inspection it looks like the problem is only for java classes that are not part of gradle or maven projects.
I was trying to debug a small program that had no need for a build tool. Is this expected behavior for nvim-java?

**Comment by Opposite34** [comment]
> @kyerpotts Sounds impossible. We retrieve the java executable information from `jdtls` meaning, if jdtls uses openjdk-21 for LS, it should be the same for run and debug as well. Has to be some cache issue. But try
> 
> ```lua
> jdk = {
>   -- install jdk using mason.nvim
>   auto_install = true,
> }
> ```
> 
> When setup. This will disable auto installation of jdk 17. Then remove the JDK from `mason`. Clear the `.classpaths`, `.projects` & `jdtls` cache. Make sure you have not set jdk-17 as the runtime in pom.xml. Try again.

I think you meant this? 
```lua
jdk = {
  -- install jdk using mason.nvim
  auto_install = false,
}
``` 
Either way, no matter the setup, mason forces installation of openjdk-17 even after doing MasonUninstall...

**Comment by s1n7ax** [comment]
@Opposite34 The reason why mason install openjdk is because `java.setup` being called twice. First time with the configuration you have provided and the second time with the default empty table. I have added validations to check if setup is being called twice. I had invalid config instructions for `LazyVim` so checkout the new config instructions to fix it.

https://github.com/nvim-java/nvim-java?tab=readme-ov-file#hammer-how-to-install

@kyerpotts For runtime thing, I assumed it will use the default in the config. Once again, this could be because `lspconfig.jdtls.setup()` is being called more than once so your configurations are overridden by consequent calls. 

Either way, I'm adding a command to change the JDK. I think I might release it today assuming I can find the time.

**Comment by s1n7ax** [comment]
Make sure to update `lazy.nvim` to latest. I'm using a new feature in `lazy.nvim` to load deps in the latest install instructions

**Comment by s1n7ax** [comment]
# Background Story

@kyerpotts @Opposite34 I tested this. Plugin actually works as I expected but `~/.cache/nvim/jdtls` has be removed upon runtime change because by default it's cached. 

This issue you are facing is actually a limitation in JDTLS. As you can see from the readme, it compiles the source using 19 class version. But when we run, you are using the 21 version and it expect the class version to be 21.

![image](https://github.com/nvim-java/nvim-java/assets/18459807/da99356a-8a2a-4c5f-9d78-f6d546511e71)

To confirm the theory, I tried Java 19 to run and it works without any issue,
![image](https://github.com/nvim-java/nvim-java/assets/18459807/8782850c-0f7c-4a37-920b-d1c0067b3eeb)

![image](https://github.com/nvim-java/nvim-java/assets/18459807/8e98ce13-296d-47b3-a25e-2c8ca892b7df)

## Temporary solution
You can use `JavaProfile` command to create a new profile to the main with `--enable-preview` vm flag.

![image](https://github.com/nvim-java/nvim-java/assets/18459807/90d8ec17-f1e8-41f0-874d-6c906ecf0c0b)

**Comment by s1n7ax** [comment]
I noticed that profile doesn't apply right away in the same session. That's a bug and obviously, I have to add `--enable-preview` for `jdtls` not supported versions. That will be done with this issue.

https://github.com/nvim-java/nvim-java/issues/241
