### ISSUE TITLE
feature: manually skip jdtls installation if it exists in path

### ISSUE THREAD

**Issue by greeid** [nvim-java/nvim-java#211]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

The `jdtls` server isn't downloading from mason (seems like a server side issue from eclipse) so i've manually added and configured `jdtsl` to $PATH but mason still tries to download jdtls on nvim startup

### Describe the solution you'd like

skip `jdtls` download from mason if `jdtls` is already on $PATH and configured

### Describe alternatives you've considered

I've tried removing `jdtls` from the `ensure_installed` option in my lspconfig but it still tries to download `jdtls` via mason

### Additional context

https://github.com/nvim-java/nvim-java/assets/58597122/ea268d9d-4daf-49e3-beb6-cce722a87561

**Comment by s1n7ax** [comment]
@greeid

Copy the url and try to download from browser. Your issue is probably unrelated to this project because even the url seems to be correct from the video. Either way make sure it's not below issue.

https://github.com/nvim-java/nvim-java/wiki/Q-&-A#no_entry-cannot-find-package-xxxxx

We are not using jdtls python script as an executable. There are various things we have to load from different paths like config, plugins etc. So having it in $PATH is not really what we want.
