### ISSUE TITLE
bug: No delegateCommandHandler fo r vscode.java.resolveMainClass

### ISSUE THREAD

**Issue by SidereaH** [nvim-java/nvim-java#321]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

Fedora 41

### Describe the bug

RPC[Error] code_name = MethodNotFound, message = "No delegateCommandHandler fo r vscode.java.resolveMainClass"
![изображение](https://github.com/user-attachments/assets/7dd3e9d9-d7cd-4f08-867e-7cfd58de8ab5)
dap configuration failed
RPC[Error] code_name = MethodNotFound, message = "No delegateCommandHandler for vscode.java.resolveMainClass"
stack traceback:
	...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:18: in function 'error_handler'
	...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:32: in function 'callback'
	...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:72: in function 'handler'
	/usr/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

### Steps To Reproduce

1. Open Java Spring project
2. Dap configuring error

### Expected Behavior

error with configuring dap

**Comment by s1n7ax** [comment]
You should remove nvim-jdtls. You cannot use both nvim-java and nvim-jdtls

**Comment by soeguet** [comment]
I just had the same problem, since I am trying out blink.cmp
In the lower nvim-lspconfig part I went with the opts = {} version to initiate nvim-java, like this:
![image](https://github.com/user-attachments/assets/0ac45c37-3a11-43d1-b529-4ebe9f66af58)

commenting that out and actually calling require('java').setup({}) in the config part of nvim-lspconfig fixed it for me:

![image](https://github.com/user-attachments/assets/5f87eef6-8af6-42de-b606-b4b016be6217)

**Comment by SidereaH** [comment]
Its can be conflicting with other Neovim setups, in my case I just reinstall LazyVim and setup nvim-java without prtoblems.

**Comment by jaimeferj** [comment]
> I just had the same problem, since I am trying out blink.cmp In the lower nvim-lspconfig part I went with the opts = {} version to initiate nvim-java, like this: ![image](https://github.com/user-attachments/assets/0ac45c37-3a11-43d1-b529-4ebe9f66af58)
> 
> commenting that out and actually calling require('java').setup({}) in the config part of nvim-lspconfig fixed it for me:
> 
> ![image](https://github.com/user-attachments/assets/5f87eef6-8af6-42de-b606-b4b016be6217)

#
I am having the same issue. Changed my configuration to match the above, but the same error happens. The project I am trying to debug is [Geoserver](https://github.com/geoserver/geoserver) which I am trying to run attach to using this configuration:

``` JSON
{
    "$schema": "https://raw.githubusercontent.com/mfussenegger/dapconfig-schema/master/dapconfig-schema.json",
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "request": "attach",
            "name": "Attach to Maven",
            "hostName": "localhost",
            "port": 8000
        }
    ]
}
```

But the error `No delegateCommandHandler for vscode.java.resolveMainClass` is just not going away

**Comment by Slava-Ini** [comment]
@soeguet solution helped me though with a little tweak like this:
`-- plugins/java.lua`
```lua
return {
  "nvim-java/nvim-java",
}
```

` --lsp.lua`
```lua
-- Some other configs ...
{
  "neovim/nvim-lspconfig",
  config = function()
    require("java").setup({})
    require("lspconfig").jdtls.setup({})
  end,
}
```

**Comment by logrusx** [comment]
I'm putting this here just for reference, because it took me quite a while to get to the answer and for other people to be able to find it easier:

This error happens when java-debug-adapter is not setup properly and particularly when its bundles are not added to jdtls. Those bundles are what provides the handler for `vscode.java.resolveMainClass` and when nvim-java tries to setup DAP, it fails with this error.

Until now this happened due to improper order of setup, nvim-java being setup after the LSP has been already configured which prevented nvim-java from doing that itself.

For the future however this mechanism seems to be going away because of the deprecation of nvim-lspconfig and the migration to the new vim.lsp API.

**Comment by MKoseler** [comment]
@logrusx  Do you have any guidance for me:
I had a working setup with java17, but I couldnt run a project because part out of my control was compiled with java21.
So I tried to switch the version to java21 by:

-   Specifying release version in pom file
```
  <properties>
    <maven.compiler.release>21</maven.compiler.release>
  </properties>
```

- deinstalling whacky homebrew java installation and installing openjdk-21 from ubuntu sources
- setting autoinstall = false in java setup
- setting the runtime to point to the java21 directory
- remove .classpath, .project, ~/.cache/jdtls and ~/.cache/nvim/jdtls

But now I also get the delegateCommandHandler error, which I didnt before. What I notice is, that ~/.cache/jdtls was not rebuilt, is that important? Below is my config which I currently have now:

```
return {
  {
    "nvim-java/nvim-java",
    config = function()
      require("java").setup({
        jdk = {
          auto_install = false,
        },
      })
      require("lspconfig").jdtls.setup({
        -- Your custom jdtls settings goes here
        init_options = {
          documentSymbol = {
            dynamicRegistration = false,
            hierarchicalDocumentSymbolSupport = true,
            labelSupport = true,
          },
        },
        settings = {
          format = {
            enabled = true,
            settings = {
              url = "vim.fn.expand('~/codestyle/opst-commons/ts-opst-commons-formatter.xml')",
              profile = "ts-opst-commons",
            },
          },
          java = {
            inlayHints = {
              parameterNames = {
                enabled = "all",
              },
            },
            configuration = {
              runtimes = {
                name = "JavaOpenJDK-21",
                path = "/usr/lib/jvm/java-21-openjdk-amd64",
                default = true,
              },
            },
          },
        },
      })
    end,
    dependencies = {
      {
        "neovim/nvim-lspconfig",
        opts = {
          servers = {
            jdtls = {},
          },
        },
      },
    },
  },
  {
    "mfussenegger/nvim-jdtls",
    enabled = false,
  },
  {
    "rcasia/neotest-java",
    enanabled = false,
  },
}

```
Thank you, help is gladly appreciated.

**Comment by s1n7ax** [comment]
Following is a map of versions we've tested to work.

```lua
jdtls = '1.43.0',
java_test = '0.40.1',
java_debug_adapter = '0.58.2',
spring_boot_tools = '1.55.1',
jdk = '17.0.2',
```

If you deviate from any of these versions, then it's your responsibility to find the working combination of versions.

`vscode.java.resolveMainClass` is a part of `java-debug` extension. So, either there is a problem installing that extension or (if it's correctly loaded) it's a version miss match.

Following commands should print all the available commands by JDTLS. In the list, you should see `vscode.java.resolveMainClass`. If you see it in the list, and still facing this issue, it's likely a version miss match. If you don't see this, it's likely that either package is not installed or failed to load the extension into JDTLS.

```lua
lua =vim.lsp.get_clients({ name = 'jdtls' })[1].server_capabilities.executeCommandProvider.commands
```

<img width="1920" height="584" alt="Image" src="https://github.com/user-attachments/assets/005f452d-3f18-474e-8d80-6f9ae712072c" />

**Comment by s1n7ax** [comment]
I'm hoping the new `vim.lsp.config` would fix these kind of config issues. I'm working on the changes needed right now. Should be ready hopefully before end of the month.

**Comment by MKoseler** [comment]
Thx for the hint at where to find the capabilities. As I dont have **any** vscode... capabilities, I suspected that the debug adapter was not loading at all.

I added the following to my configuration, and now the error is gone and dap is working:

```
require("lspconfig").jdtls.setup({
        -- Your custom jdtls settings goes here
        init_options = {
          documentSymbol = {
            --dynamicRegistration = false,
            hierarchicalDocumentSymbolSupport = true,
            labelSupport = true,
          },
          bundles = {
            "/home/<username>/.local/share/nvim/mason/packages/java-debug-adapter/extension/server/com.microsoft.java.debug.plugin-0.53.2.jar",
          },
        },
```
Maybe because I set the init_options explicitly, in order to have documentSymbol support for telescope browse lsp symbols, I overwrote the default config and the debug adapter was not bundled with jdtls anymore? 

EDIT: However, no when I try to run a test method, I dont have capabilities to find testTypesAndMethods - is this not supported in the 0.53.2 java debug plugin? Other vscode capabilities are now available, but this one is  missing.

No delegateCommandHandler for vscode.java.test.findTestTypesAndMethods

> Following is a map of versions we've tested to work.
> 
> jdtls = '1.43.0',
> java_test = '0.40.1',
> java_debug_adapter = '0.58.2',
> spring_boot_tools = '1.55.1',
> jdk = '17.0.2',
> If you deviate from any of these versions, then it's your responsibility to find the working combination of versions.
> 
> `vscode.java.resolveMainClass` is a part of `java-debug` extension. So, either there is a problem installing that extension or (if it's correctly loaded) it's a version miss match.
> 
> Following commands should print all the available commands by JDTLS. In the list, you should see `vscode.java.resolveMainClass`. If you see it in the list, and still facing this issue, it's likely a version miss match. If you don't see this, it's likely that either package is not installed or failed to load the extension into JDTLS OR version miss match.
> 
> lua =vim.lsp.get_clients({ name = 'jdtls' })[1].server_capabilities.executeCommandProvider.commands
> <img alt="Image" width="1920" height="584" src="https://private-user-images.githubusercontent.com/18459807/517210111-005f452d-3f18-474e-8d80-6f9ae712072c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM3MjA5OTgsIm5iZiI6MTc2MzcyMDY5OCwicGF0aCI6Ii8xODQ1OTgwNy81MTcyMTAxMTEtMDA1ZjQ1MmQtM2YxOC00NzRlLThkODAtNmY5YWU3MTIwNzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTIxVDEwMjQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NTUyOTg3NWRlZmVkYzM1MWY2ZGI0M2IwNzUzNGM4NjAzNDQ3N2I4ZDM3NzUxZmNiM2JmOTQzYjM4Njc5ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.irYqWDGcB_-U5q1GjeezfFvhiUIe-Scn-ywz94zz4D4">

**Comment by logrusx** [comment]
Another thing I've found is there are problems with custom jdtls settings. Try first removing the init options completely, then start adding them gradually to see where it breaks. It may also be useful if you can report it.

**Comment by MKoseler** [comment]
Aha! I've found the solution in the nvim-jdtls readme, I needed to bundle more jars besides the vscode-test-plugin. Working init_options for jdtls below (basically copy&paste from nvim-jdtls readme):

```
      local bundles = {
        vim.fn.glob(
          "/home/<username>/.local/share/nvim/mason/packages/java-debug-adapter/extension/server/com.microsoft.java.debug.plugin-*.jar",
          1
        ),
      }
      -- This is the new part
      local java_test_bundles = vim.split(vim.fn.glob("/home/<username>/server/*.jar", 1), "\n")
      local excluded = {
        "com.microsoft.java.test.runner-jar-with-dependencies.jar",
        "jacocoagent.jar",
      }
      for _, java_test_jar in ipairs(java_test_bundles) do
        local fname = vim.fn.fnamemodify(java_test_jar, ":t")
        if not vim.tbl_contains(excluded, fname) then
          table.insert(bundles, java_test_jar)
        end
      end
      require("lspconfig").jdtls.setup({
        -- Your custom jdtls settings goes here
        init_options = {
          documentSymbol = {
            --dynamicRegistration = false,
            hierarchicalDocumentSymbolSupport = true,
            labelSupport = true,
          },
          bundles = bundles,
        },
        ...
```
